spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/springboot_server?characterEncoding=utf8&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true

    schema: classpath:db/schema.sql
    #    data: classpath:db/data.sql

    username: root
    password: william
    initialize: true
    initialization-mode: always
